name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build and run services
        run: docker compose up --build -d

      - name: Run unit tests (kitchen_service)
        run: docker compose exec -T kitchen_service pytest tests --maxfail=1 --disable-warnings -q

      - name: Run unit tests (order_service)
        run: docker compose exec -T order_service pytest tests --maxfail=1 --disable-warnings -q
